version: "3.9"
services:
  mescobrad_edge:
    image: mescobrad-edge
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /usr/src/app/mescobrad_edge/plugins
      - /usr/src/app/mescobrad_edge/workflows
    environment:
      - PYTHONUNBUFFERED=1

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ""
      MINIO_ROOT_PASSWORD: ""
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}